### ISSUE TITLE
Panic when subscribing to page

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/amfora#151]
Hello @makeworld-the-better-one 
congrats on the new release!

I was trying out the subscription feat. It works well with an atom feed (tested on makeworld.gq) but when subscribing to a page it consistently panics every time, leaving a mess in the terminal.

Windows 10, launched from Powershell

Amfora 1.7.0
Commit: c93d09b26ba96d3eb77e8b85c812f739170537b8
Built by: goreleaser

Screenshot:
![WindowsTerminal_2zthca7b2t](https://user-images.githubusercontent.com/6209647/102803510-a23ecc00-43b8-11eb-8f63-2a8d774bca08.png)

Thanks

**Comment by makeworld-the-better-one** [comment]
Damn, thanks for reporting. m15o reported a similar bug (before the release), with this screenshot:

![subscription](https://user-images.githubusercontent.com/25111343/102804596-f54c5b00-4387-11eb-91b9-31a31532026f.png)

I have no issues subscribing to pages on my side, so I assumed they were running off of an older commit and made the release anyway. Looking at the screenshot again, it seem clear they were running off an older commit, as some of the lines referenced don't make sense. For example, `subscriptions/subscriptions.go:215` currently just has a comment on it.

The current line actually causing the error appears to be 218, and it happens when you have no entries, then add a feed, close Amfora, and then open it and try to add a page. I have confirmed this error happens on my machine as well. I will fix this ASAP and then make a new release.

**Comment by makeworld-the-better-one** [comment]
I have release v1.7.1 with this fix.

**Comment by Jackymancs4** [comment]
Nice, I will try the new release on my Windows setup by tomorrow.

**Comment by makeworld-the-better-one** [comment]
Thanks! I was able to replicate the error and then see the fix, so I don't expect any issues. But testing is always appreciated of course.

**Comment by Jackymancs4** [comment]
Indeed, 1.7.1 works great!
