### ISSUE TITLE
Support empty <META> string

### ISSUE THREAD

**Issue by leifmetcalf** [makeworld-the-better-one/amfora#176]
The gemini spec says
> f <META> is an empty string, the MIME type MUST default to "text/gemini; charset=utf-8". The text/gemini media type is defined in section 5.

But it seems like amfora doesn't do this.

**Comment by makeworld-the-better-one** [comment]
Thanks for bringing this up! I should've handled this a long time ago. Maybe I did and it got changed? Anyway...

If you had a test page for this that would be helpful, as I currently have no way to test this.

**Comment by panda-roux-dev** [comment]
@makeworld-the-better-one  Would you mind re-opening this?  I don't mind fixing it myself once I get a Go dev environment set up.

You can test it on one of my capsules: gemini://library.inu.red/browse

Because of a quirk of how I built MoonGem's scripting API, that page will return a header consisting solely of `20` followed by the carriage return.

**Comment by panda-roux-dev** [comment]
You know what, this is actually an issue go-gemini.  Disregard this; I'll open an issue there.

https://github.com/makeworld-the-better-one/go-gemini/blob/156d3096e40b1a88eaa5c45cf91a387c3a901941/client.go#L422
