### ISSUE TITLE
Using the user's terminal colors

### ISSUE THREAD

**Issue by Zambito1** [makeworld-the-better-one/amfora#181]
Thank you for making Amfora, it is quite a nice browser!

I saw you mention that [you were having trouble using the users terminal colors](https://github.com/makeworld-the-better-one/amfora/issues/46#issuecomment-665279904). It seems that when launching the terminal over SSH, it properly uses the users terminal colors. Maybe this can uncover some way that it can be done an easier way.

Both terminals are here are Alacritty, using the Nord colors. The left is using ssh to open Amfora, the right is not.
![Screenshot of two amfora windows, the left using the terminals colors, the right using default black with high contrast](https://user-images.githubusercontent.com/7004857/107102383-5e791800-67e8-11eb-8102-9817b24164d3.png)

**Comment by makeworld-the-better-one** [comment]
I believe this how to do with how tcell (low-level terminal library, used by Amfora and the TUI middle-layer library called cview) works. In a normal terminal it can check for truecolor support and attempt to display the original color. Over SSH, tcell thinks truecolor isn't supported, and it will fallback to the regular color codes, which the terminal will then display using the built-in palette. That's my guess, anyway.

IIRC the reason Amfora doesn't try to use default terminal colors is that it's hard to get both light and dark terminals to work correctly. There's not really a way to know whether to use white text or black text for example, and I believe that just trying to use terminal colors will mess up in certain situations, like put white text on the default white terminal background. I might be wrong about that, and it's worth looking into. But it's easier to just use truecolor and provide support for themeing. For example, there is a [Nord theme](https://github.com/makeworld-the-better-one/amfora/tree/master/contrib/themes#nord). But I understand that's annoying to create for other terminal setups.

I leave this open as a question for now, something that should be tested more. Currently I am updating tcell in #107, and right now I've set things up so truecolor is forced whenever possible, ignoring the user's terminal colors.

**Comment by objectliteral** [comment]
I second the request for respecting the terminal's color scheme, but I agree that doing so is not without some limitations.

> But it's easier to just use truecolor and provide support for themeing.

It's slightly annoying for users to go to each application's config and tweak the color scheme to match the rest of their systems. Especially so if they have set up some kind of automation like with pywal.

> IIRC the reason Amfora doesn't try to use default terminal colors is that it's hard to get both light and dark terminals to work correctly. There's not really a way to know whether to use white text or black text for example, and I believe that just trying to use terminal colors will mess up in certain situations, like put white text on the default white terminal background.

I don't think that will be a problem since you're setting a background color anyway, so might as well use one that fits the user's color scheme. tcell can take color names for 4bit colors which will then be rendered by the terminal according to the terminal's settings. The default theme in Amfora could simply be changed to use color names instead of hex codes and look consistent (i.e. no white text on white bg) as long as the user has their terminal colors configured properly. The only problem is that there is no reliable way to tell whether the user would prefer a dark or light color scheme (but that problem exists with the current schemes anyway). But including a light and a dark default scheme using color names seems an easy solution. (A more advanced approach might be to peak at some common terminal config files to deduce the user's preference, but that is an optional improvement).

Does this make sense?

Oh and in any case: Changing the default colorscheme - or any default for that matter - tends to make people angry. But at least additionally bundling a light and dark scheme defined using color names could be convenient.

**Comment by makeworld-the-better-one** [comment]
Likely sounds like a good idea. I'll experiment and see when I can and report back here.

**Comment by objectliteral** [comment]
I looked a bit into how tcell handles colors and the tldr is that this does not seem easily possible with tcell v1 but will be possible with v2 (which is part of the cview-update to Amfora which is being worked on afaict).

While you *can* give tcell color names, it does map them to 24bit colors in a predefined manner and communicates them to the terminal in truecolor mode (if supported by the terminal).

They [changed this behavior with v2](https://github.com/gdamore/tcell/blob/master/CHANGESv2.adoc#better-support-for-palettes-themes)  so that using color names should cause the proper escape codes to be sent that don't use truecolor. A quick little test that I did with tcell v2 confirmed that it behaved as expected.

**Comment by makeworld-the-better-one** [comment]
Related: #116

**Comment by rasa-silva** [comment]
From some quick tests I made with tcell, I had good results simply by exporting `TCELL_TRUECOLOR=disable`. See [here](https://pkg.go.dev/github.com/gdamore/tcell/v2@v2.0.0-dev).
Bear in mind that having worked well for me doesn't exactly mean it's the correct way of doing this...
Just putting it here in case someone wants to try it.

**Comment by makeworld-the-better-one** [comment]
Note: This should also allow for transparent terminals to stay transparent, if possible.

**Comment by makeworld-the-better-one** [comment]
#245 by @m-mcdonagh will allow for using the terminal's default background color, including transparent backgrounds.

The next step after this PR would be figuring out how to make the `default` key work for text color as well.

**Comment by makeworld-the-better-one** [comment]
With 2e1049b this issue is basically complete. I'm leaving it open because I think I can solve the issue of light and dark themes, and get those to work too.

**Comment by makeworld-the-better-one** [comment]
Light terminal backgrounds handled in 6666ef2.

Would appreciate testing of these features!

cc @m-mcdonagh

**Comment by ayushnix** [comment]
I'm using Amfora on a default light terminal theme (without any theme configuration in the amfora TOML file) and although it mostly looks fine, the background and foreground color of selected links aren't accessible.

Here's an image of a non-Gemini link when it's selected:

![a screenshot of amfora with a light terminal theme; the selected non-Gemini link colors aren't accessible](https://github.com/makew0rld/amfora/assets/79408161/951c856f-fcfe-4d8e-a638-85c1f2846036)

And here's an image of a Gemini link:

![a screenshot of amfora with a light terminal theme; the selected Gemini link colors aren't accessible](https://github.com/makew0rld/amfora/assets/79408161/8f9e12c6-df1d-4275-bf0b-b39988731685)

I'd rather not create a theme for amfora which would just add another configuration file I have to consider changing when changing my theme globally. Which terminal colors is Amfora choosing for the foreground and background of links when they are highlighted?
