### ISSUE TITLE
Support for URL fragments

### ISSUE THREAD

**Issue by GoodClover** [makeworld-the-better-one/amfora#206]
At current Amfora doesn't support URL fragments, and just strips them from the URL.

e.g, if I try to go to `https://gemini.circumlunar.space/#Geminispace%20aggregators`, amfora will remove the `#Geminispace%20aggregators` from the end.

It would be nice if support for these was added, ideally it would load the page as normal pre-scrolled to the correct section of the page with that heading.

**Comment by makeworld-the-better-one** [comment]
I would like to support this as well. Unfortunately there is no standard in Gemini for how to link to headers. That would need to be established before this could become useful, as otherwise no one would know how to link to headers in a compatible way. I should probably just write up an idea and propose it, but until then this feature cannot be supported.

To clarify, I'm talking about a standard that turns the text of a header until a URL-safe fragment. What to do with spaces, with Unicode characters, with multiple headings with the same name, etc.

**Comment by GoodClover** [comment]
Wouldn't this just follow the standard URL fragment pattern?
Encoding the text as URL/URI is already solved, that's a part of their own specs.
And for how the fragments work I assume it would be the same as with the web? Gemtext isn't complex enough to do it any other way.
Probably good to discuss on the Gemini list first, yeah though :)

**Comment by makeworld-the-better-one** [comment]
On the Web, the URL fragment tells the browser to navigate to the HTML element with the id that matches the fragment. For gemtext, there is no standard for browsers to match fragments to headings. I plan on writing one, publishing it, and proposing it.

**Comment by makeworld-the-better-one** [comment]
@GoodClover I've made a new issue for this, see #286
