### ISSUE TITLE
Binding tab 4 to '¤' doesn't work (non-US layout)

### ISSUE THREAD

**Issue by morngrar** [makeworld-the-better-one/amfora#217]
Configured correctly, other characters that aren't too far out from regular use also work, however this one, which is my Shift-4 character doesn't work at all

**Comment by makeworld-the-better-one** [comment]
This should actually be fixed in the master branch, see #198. There's [instructions](https://github.com/makeworld-the-better-one/amfora#from-source) on the README for how to try it out if you're up for it. If you do try it, let me know if it works! It should.

Otherwise, I can send you binary myself if you let me know your OS and architecture. Once v1.9.0 is out it will have this fix included.

**Comment by morngrar** [comment]
> This should actually be fixed in the master branch, see #198. There's [instructions](https://github.com/makeworld-the-better-one/amfora#from-source) on the README for how to try it out if you're up for it. If you do try it, let me know if it works! It should.
> 
> Otherwise, I can send you binary myself if you let me know your OS and architecture. Once v1.9.0 is out it will have this fix included.

That worked smoothly! thanks
