### ISSUE TITLE
History of visited sites

### ISSUE THREAD

**Issue by lodenrogue** [makeworld-the-better-one/amfora#228]
Great tool and great work everyone. I tried out this browser today and loved it. I see in the todo list there are plans to implement saving persistent history. I think this is would be extremely useful. Any updates on when this would be worked on?

**Comment by makeworld-the-better-one** [comment]
Glad you're enjoying it!

There are no updates on that feature. It's something I'd like to implement, but I haven't gotten around to it, and there are more pressing issues. If anyone would like to try and implement it themselves they could contact me to discuss details, and I would be happy to review a PR. Otherwise I will get to it eventually.

**Comment by lodenrogue** [comment]
Thanks for getting back. Would a donation of any size help convince you to make this the top priority?
