### ISSUE TITLE
When bookmarking a page, suggest a title based on the first level 1 heading

### ISSUE THREAD

**Issue by mntn-xyz** [makeworld-the-better-one/amfora#267]
I usually just retype a short version of the heading, what do other people do?

**Comment by makeworld-the-better-one** [comment]
I often write something custom, but this is a good suggestion. Low priority but something that would be nice to have for sure.

**Comment by makeworld-the-better-one** [comment]
Also, if this was added, there would have to be some way to show that the bookmark already exists when pressing Ctrl-D on a page. Right now I'm able to tell when a bookmark is already there because the text of the bookmark title shows up pre-filled. If this was added there would almost always be something pre-filled.

**Comment by mntn-xyz** [comment]
Currently for existing bookmarks it shows a "change or remove" dialog (with the current bookmark name) instead of the "add" dialog.

**Comment by makeworld-the-better-one** [comment]
Oh yeah ha, good point.
