### ISSUE TITLE
feature request: ARM port

### ISSUE THREAD

**Issue by teslasmoustache** [makeworld-the-better-one/amfora#273]
Hi. I'd like to be able to use Amfora on my Raspberry Pi. And seeing as how Gemini is fairly lightweight, it stands to reason that such a platform could conceivably handle it...better than how it's handling typing this message in Firefox on a Pi right now...

**Comment by makeworld-the-better-one** [comment]
Happy to report that Amfora already runs well on the Raspberry Pi. You'll want to download the binary that's named `linux_armv7`. That will work for RPi 2, 3, and 4 running Raspberry Pi OS. `linux_armv6` will also work, but isn't as optimized. `linux_armv6` is required for some older Pis though. See [this table](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications) for details. Note that `arm64`, aka ARMv8, will not work with Raspberry Pi OS because it's not a 64-bit OS.

Here's the download link for Amfora v1.8.0 for the ARMv7 architecture: https://github.com/makeworld-the-better-one/amfora/releases/download/v1.8.0/amfora_1.8.0_linux_armv7

Building from source will also work fine on a Raspberry Pi.

Let me know if you have any other questions or issues!

**Comment by teslasmoustache** [comment]
"if it was a snake it woulda bit me"

sorry about that.
