### ISSUE TITLE
Error: "Not a valid 'about:' URL" when trying to open the 7th link from `New Tab` page

### ISSUE THREAD

**Issue by bzbug** [makeworld-the-better-one/amfora#306]
1. Open new tab in `amfora` (`about:newtab`). Default page for new tab should open.
2. Enter command mode (where you can issue commands in the bar at the bottom), by default it's done by pressing `<Space>`.
3. Enter `new:7` in command mode to open the 7th link from the default new tab page in new tab.
4. The 7th link is displayed as `//gemini.circumlunar.space` at the bottom bar, but if I copy it and paste it here it will be `about://gemini.circumlunar.space`. After issuing the command it doesn't open in new tab, instead an error is shown that says: `Not a valid 'about:' URL.`

![894x499_ 10 04 2022 18:32](https://user-images.githubusercontent.com/28236673/162624366-b7cc6881-88f4-4312-bda6-f81d963ecaf4.png)

However, just using the `7` default key to open the link in current tab (instead of the command in the bottom bar) works fine. Opening the link in new tab via a hotkey (enter link hinting mode, navigate to the 7th link, use the hotkey for opening it in a new tab) also works well.

**Comment by mntn-xyz** [comment]
Starting a URL with // (without a specified protocol) means to open the link using the current protocol. This even works with HTTP/HTTPS links in compliant browsers. Because the protocol is not specified, these links only work if you open them from another page. If you copy/paste the link, you would have to add a protocol.

It looks like the about page can probably just specify the gemini: protocol since there's no reason to use the protocol-relative URL here, unless amfora knows of a reason.

**Comment by makeworld-the-better-one** [comment]
Yeah this is definitely a bug, thanks. It's incorrect for me to start the URL with `//` because the scheme is literally `about:`, but all ways to open the link should either fail or all should succeed, having only `new:7` cause the error is a problem. Will fix.
