### ISSUE TITLE
Make `about:newtab` easier to get to

### ISSUE THREAD

**Issue by adiabatic** [makeworld-the-better-one/amfora#96]
Occasionally I've wanted to go back to that page that's first shown on startup, but I only stumbled on "about:newtab" by accident and pressing `b` repeatedly won't take me there.

Would it be possible and/or a good idea (on net) to display `about:newtab` in the address bar at the bottom and/or make the new-tab page accessible by pressing `b` a bunch of times?

**Comment by makeworld-the-better-one** [comment]
Yep, it should be possible. I deliberately didn't add the newtab page to history so you can't navigate back to it, but I guess there's no harm in allowing it.

I didn't display `about:newtab` in the address bar because I thought it's cleaner not to have it at the beginning, similar to how the address bar is empty in web browsers when you open a new tab.

**Comment by sotpapathe** [comment]
Also interested in this, might work on it sometime soon. Until then, a good workaround is setting the homepage to `about:newtab`.

**Comment by makeworld-the-better-one** [comment]
This was fixed in 95f077c. You can now go back to the new tab page. This will be in the next release, v1.7.0. Hope this addresses your issue!
